In [1]:
import seaborn as sns
import pandas as pd

In [2]:
healthexp = sns.load_dataset('healthexp')
healthexp

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

In [3]:
healthexp = pd.get_dummies(healthexp, dtype=int)
healthexp

,Year,Spending_USD,Life_Expectancy,Country_Canada,Country_France,Country_Germany,Country_Great Britain,Country_Japan,Country_USA
0,1970,252.311,70.6,0,0,1,0,0,0
1,1970,192.143,72.2,0,1,0,0,0,0
2,1970,123.993,71.9,0,0,0,1,0,0
3,1970,150.437,72.0,0,0,0,0,1,0
4,1970,326.961,70.9,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...
269,2020,6938.983,81.1,0,0,1,0,0,0
270,2020,5468.418,82.3,0,1,0,0,0,0
271,2020,5018.700,80.4,0,0,0,1,0,0
272,2020,4665.641,84.7,0,0,0,0,1,0
273,2020,11859.179,77.0,0,0,0,0,0,1

In [4]:
X = healthexp.drop(['Life_Expectancy'], axis=1)
y = healthexp['Life_Expectancy']

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=54)

In [7]:
from sklearn.ensemble import RandomForestRegressor
rfr= RandomForestRegressor(random_state=34)

In [8]:
rfr.fit(X_train, y_train)

RandomForestRegressor(random_state=34)

In [9]:
y_pred = rfr.predict(X_test)

In [10]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [11]:
mean_absolute_error(y_test, y_pred)

0.31138181818180044

In [12]:
mean_squared_error(y_test, y_pred)

0.1553235999999905

In [13]:
r2_score(y_test, y_pred)

0.9836234548107303

In [14]:
import optuna 
from sklearn.model_selection import cross_val_score

In [21]:
def objective(trial):
    n_estimators = trial.suggest_int('n_estimators', 100,1000)
    max_depth = trial.suggest_int('max_depth', 10,50)
    min_samples_split = trial.suggest_int('min_samples_split', 2,32)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1,32)

    model = RandomForestRegressor(n_estimators=n_estimators,
                                 max_depth=max_depth,
                                 min_samples_split=min_samples_split,
                                 min_samples_leaf=min_samples_leaf)
    score = cross_val_score(model, X_train, y_train, cv=5, scoring='neg_mean_squared_error' ,n_jobs=-1).mean()
    return score

In [22]:
study = optuna.create_study(direction='maximize', sampler= optuna.samplers.RandomSampler(seed=42))

[I 2026-03-12 03:48:29,992] A new study created in memory with name: no-name-15e2bd32-093d-4662-b67c-63779d90d7c9

In [23]:
study.optimize(objective, n_trials=200)

[I 2026-03-12 03:48:36,365] Trial 0 finished with value: -2.309741991023285 and parameters: {'n_estimator': 437, 'max_depth': 48, 'min_samples_split': 24, 'min_samples_leaf': 20}. Best is trial 0 with value: -2.309741991023285.
[I 2026-03-12 03:48:37,500] Trial 1 finished with value: -2.9034630474207574 and parameters: {'n_estimator': 240, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 28}. Best is trial 0 with value: -2.309741991023285.
[I 2026-03-12 03:48:40,081] Trial 2 finished with value: -3.325201852407365 and parameters: {'n_estimator': 641, 'max_depth': 39, 'min_samples_split': 2, 'min_samples_leaf': 32}. Best is trial 0 with value: -2.309741991023285.
[I 2026-03-12 03:48:43,785] Trial 3 finished with value: -1.0133606571897464 and parameters: {'n_estimator': 850, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:48:45,399] Trial 4 finished with value: -1.56398413329412 and parameters: {'n_estimator': 374, 'max_depth': 31, 'min_samples_split': 15, 'min_samples_leaf': 10}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:48:48,131] Trial 5 finished with value: -1.8116814532650711 and parameters: {'n_estimator': 651, 'max_depth': 15, 'min_samples_split': 11, 'min_samples_leaf': 12}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:48:50,202] Trial 6 finished with value: -2.1893659760773567 and parameters: {'n_estimator': 510, 'max_depth': 42, 'min_samples_split': 8, 'min_samples_leaf': 17}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:48:52,881] Trial 7 finished with value: -1.131755317283828 and parameters: {'n_estimator': 633, 'max_depth': 11, 'min_samples_split': 20, 'min_samples_leaf': 6}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:48:53,541] Trial 8 finished with value: -2.685209863367126 and parameters: {'n_estimator': 158, 'max_depth': 48, 'min_samples_split': 31, 'min_samples_leaf': 26}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:48:55,133] Trial 9 finished with value: -2.074092092520939 and parameters: {'n_estimator': 374, 'max_depth': 14, 'min_samples_split': 23, 'min_samples_leaf': 15}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:48:55,995] Trial 10 finished with value: -3.141819373118881 and parameters: {'n_estimator': 209, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 30}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:48:57,405] Trial 11 finished with value: -2.2102653738289653 and parameters: {'n_estimator': 333, 'max_depth': 37, 'min_samples_split': 11, 'min_samples_leaf': 17}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:48:59,749] Trial 12 finished with value: -2.595159061125592 and parameters: {'n_estimator': 592, 'max_depth': 17, 'min_samples_split': 32, 'min_samples_leaf': 25}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:49:03,453] Trial 13 finished with value: -3.137154540812293 and parameters: {'n_estimator': 946, 'max_depth': 46, 'min_samples_split': 20, 'min_samples_leaf': 30}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:49:04,212] Trial 14 finished with value: -1.6877276232680676 and parameters: {'n_estimator': 179, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 11}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:49:06,068] Trial 15 finished with value: -1.8384057908854445 and parameters: {'n_estimator': 450, 'max_depth': 21, 'min_samples_split': 27, 'min_samples_leaf': 12}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:49:07,538] Trial 16 finished with value: -2.691827330924409 and parameters: {'n_estimator': 353, 'max_depth': 32, 'min_samples_split': 6, 'min_samples_leaf': 26}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:49:08,267] Trial 17 finished with value: -1.3510513592812765 and parameters: {'n_estimator': 167, 'max_depth': 50, 'min_samples_split': 25, 'min_samples_leaf': 7}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:49:08,712] Trial 18 finished with value: -2.54244119649474 and parameters: {'n_estimator': 104, 'max_depth': 43, 'min_samples_split': 23, 'min_samples_leaf': 24}. Best is trial 3 with value: -1.0133606571897464.
[I 2026-03-12 03:49:12,182] Trial 19 finished with value: -0.6694371381704046 and parameters: {'n_estimator': 794, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 19 with value: -0.6694371381704046.
[I 2026-03-12 03:49:15,998] Trial 20 finished with value: -0.5222380584141824 and parameters: {'n_estimator': 877, 'max_depth': 35, 'min_samples_split': 12, 'min_samples_leaf': 3}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:17,606] Trial 21 finished with value: -2.3574343291987607 and parameters: {'n_estimator': 380, 'max_depth': 23, 'min_samples_split': 24, 'min_samples_leaf': 21}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:21,185] Trial 22 finished with value: -2.4581770150984448 and parameters: {'n_estimator': 899, 'max_depth': 29, 'min_samples_split': 5, 'min_samples_leaf': 23}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:24,351] Trial 23 finished with value: -2.1358881695366625 and parameters: {'n_estimator': 785, 'max_depth': 33, 'min_samples_split': 25, 'min_samples_leaf': 16}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:26,905] Trial 24 finished with value: -0.5898599780380069 and parameters: {'n_estimator': 570, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:27,451] Trial 25 finished with value: -2.1814329818882765 and parameters: {'n_estimator': 128, 'max_depth': 36, 'min_samples_split': 11, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:31,071] Trial 26 finished with value: -2.597053404520785 and parameters: {'n_estimator': 917, 'max_depth': 20, 'min_samples_split': 14, 'min_samples_leaf': 25}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:32,409] Trial 27 finished with value: -1.0317756872803228 and parameters: {'n_estimator': 306, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:36,071] Trial 28 finished with value: -2.926444455742402 and parameters: {'n_estimator': 937, 'max_depth': 43, 'min_samples_split': 21, 'min_samples_leaf': 28}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:39,454] Trial 29 finished with value: -2.2396233262963805 and parameters: {'n_estimator': 824, 'max_depth': 17, 'min_samples_split': 29, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:43,044] Trial 30 finished with value: -0.6144979102912439 and parameters: {'n_estimator': 827, 'max_depth': 46, 'min_samples_split': 11, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:44,261] Trial 31 finished with value: -2.8878688498840983 and parameters: {'n_estimator': 305, 'max_depth': 27, 'min_samples_split': 27, 'min_samples_leaf': 28}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:44,747] Trial 32 finished with value: -1.3505939114680308 and parameters: {'n_estimator': 106, 'max_depth': 30, 'min_samples_split': 14, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:45,628] Trial 33 finished with value: -1.828668200391165 and parameters: {'n_estimator': 207, 'max_depth': 23, 'min_samples_split': 31, 'min_samples_leaf': 11}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:47,942] Trial 34 finished with value: -3.344492149160493 and parameters: {'n_estimator': 567, 'max_depth': 38, 'min_samples_split': 13, 'min_samples_leaf': 32}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:51,970] Trial 35 finished with value: -1.569469467245313 and parameters: {'n_estimator': 967, 'max_depth': 20, 'min_samples_split': 17, 'min_samples_leaf': 10}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:53,471] Trial 36 finished with value: -2.196584399024783 and parameters: {'n_estimator': 356, 'max_depth': 11, 'min_samples_split': 20, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:54,088] Trial 37 finished with value: -1.5720917530099148 and parameters: {'n_estimator': 146, 'max_depth': 21, 'min_samples_split': 30, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:55,070] Trial 38 finished with value: -1.607896387881936 and parameters: {'n_estimator': 230, 'max_depth': 30, 'min_samples_split': 32, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:57,926] Trial 39 finished with value: -2.521969635190132 and parameters: {'n_estimator': 705, 'max_depth': 41, 'min_samples_split': 9, 'min_samples_leaf': 24}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:49:59,690] Trial 40 finished with value: -2.224612217036124 and parameters: {'n_estimator': 431, 'max_depth': 35, 'min_samples_split': 21, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:00,522] Trial 41 finished with value: -1.002070490136123 and parameters: {'n_estimator': 181, 'max_depth': 44, 'min_samples_split': 11, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:01,151] Trial 42 finished with value: -0.9257255938379855 and parameters: {'n_estimator': 136, 'max_depth': 34, 'min_samples_split': 23, 'min_samples_leaf': 1}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:03,619] Trial 43 finished with value: -1.18128213925774 and parameters: {'n_estimator': 561, 'max_depth': 19, 'min_samples_split': 22, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:06,723] Trial 44 finished with value: -1.4078921959736903 and parameters: {'n_estimator': 722, 'max_depth': 25, 'min_samples_split': 31, 'min_samples_leaf': 5}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:08,458] Trial 45 finished with value: -2.9853131450746986 and parameters: {'n_estimator': 407, 'max_depth': 14, 'min_samples_split': 30, 'min_samples_leaf': 29}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:09,879] Trial 46 finished with value: -2.230119085073109 and parameters: {'n_estimator': 332, 'max_depth': 37, 'min_samples_split': 27, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:12,276] Trial 47 finished with value: -3.038655652167852 and parameters: {'n_estimator': 577, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 29}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:16,141] Trial 48 finished with value: -1.795326382518867 and parameters: {'n_estimator': 911, 'max_depth': 35, 'min_samples_split': 12, 'min_samples_leaf': 12}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:19,240] Trial 49 finished with value: -2.584594468090395 and parameters: {'n_estimator': 754, 'max_depth': 46, 'min_samples_split': 29, 'min_samples_leaf': 25}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:21,950] Trial 50 finished with value: -3.0353206444069523 and parameters: {'n_estimator': 678, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 29}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:24,574] Trial 51 finished with value: -2.3918406092582956 and parameters: {'n_estimator': 646, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 22}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:25,028] Trial 52 finished with value: -2.4388496706715492 and parameters: {'n_estimator': 104, 'max_depth': 16, 'min_samples_split': 19, 'min_samples_leaf': 23}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:27,955] Trial 53 finished with value: -1.464053971604896 and parameters: {'n_estimator': 687, 'max_depth': 19, 'min_samples_split': 24, 'min_samples_leaf': 8}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:29,526] Trial 54 finished with value: -2.92589503359776 and parameters: {'n_estimator': 393, 'max_depth': 40, 'min_samples_split': 22, 'min_samples_leaf': 28}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:32,366] Trial 55 finished with value: -1.8068302853079619 and parameters: {'n_estimator': 692, 'max_depth': 33, 'min_samples_split': 4, 'min_samples_leaf': 12}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:33,735] Trial 56 finished with value: -2.009502724521154 and parameters: {'n_estimator': 338, 'max_depth': 20, 'min_samples_split': 32, 'min_samples_leaf': 13}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:37,428] Trial 57 finished with value: -2.1922130133412905 and parameters: {'n_estimator': 903, 'max_depth': 35, 'min_samples_split': 26, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:39,911] Trial 58 finished with value: -2.5212791313932477 and parameters: {'n_estimator': 619, 'max_depth': 30, 'min_samples_split': 8, 'min_samples_leaf': 24}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:41,433] Trial 59 finished with value: -1.1782636872666086 and parameters: {'n_estimator': 352, 'max_depth': 10, 'min_samples_split': 22, 'min_samples_leaf': 6}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:45,350] Trial 60 finished with value: -1.873486087151214 and parameters: {'n_estimator': 947, 'max_depth': 49, 'min_samples_split': 30, 'min_samples_leaf': 12}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:45,814] Trial 61 finished with value: -3.2413532542551784 and parameters: {'n_estimator': 113, 'max_depth': 48, 'min_samples_split': 15, 'min_samples_leaf': 31}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:49,836] Trial 62 finished with value: -1.916164550915068 and parameters: {'n_estimator': 968, 'max_depth': 44, 'min_samples_split': 11, 'min_samples_leaf': 13}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:53,342] Trial 63 finished with value: -2.2341080074441897 and parameters: {'n_estimator': 866, 'max_depth': 22, 'min_samples_split': 7, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:50:57,380] Trial 64 finished with value: -0.8337040832528988 and parameters: {'n_estimator': 943, 'max_depth': 38, 'min_samples_split': 19, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:51:00,007] Trial 65 finished with value: -2.1928143957199735 and parameters: {'n_estimator': 654, 'max_depth': 50, 'min_samples_split': 6, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:51:03,568] Trial 66 finished with value: -2.450509341483884 and parameters: {'n_estimator': 890, 'max_depth': 40, 'min_samples_split': 23, 'min_samples_leaf': 23}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:51:05,262] Trial 67 finished with value: -2.6756019196693375 and parameters: {'n_estimator': 423, 'max_depth': 22, 'min_samples_split': 27, 'min_samples_leaf': 26}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:51:08,908] Trial 68 finished with value: -2.1785601704374606 and parameters: {'n_estimator': 881, 'max_depth': 47, 'min_samples_split': 17, 'min_samples_leaf': 17}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:51:12,134] Trial 69 finished with value: -2.7008122823479765 and parameters: {'n_estimator': 819, 'max_depth': 36, 'min_samples_split': 23, 'min_samples_leaf': 26}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:51:16,029] Trial 70 finished with value: -0.6612603994822391 and parameters: {'n_estimator': 901, 'max_depth': 23, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:51:18,569] Trial 71 finished with value: -2.232784089700538 and parameters: {'n_estimator': 621, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 18}. Best is trial 20 with value: -0.5222380584141824.
[I 2026-03-12 03:51:20,262] Trial 72 finished with value: -0.2615601115545077 and parameters: {'n_estimator': 358, 'max_depth': 34, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:23,618] Trial 73 finished with value: -2.1910009485924897 and parameters: {'n_estimator': 841, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 17}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:27,006] Trial 74 finished with value: -0.860935491868101 and parameters: {'n_estimator': 793, 'max_depth': 18, 'min_samples_split': 21, 'min_samples_leaf': 3}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:27,603] Trial 75 finished with value: -2.3719202345276886 and parameters: {'n_estimator': 146, 'max_depth': 31, 'min_samples_split': 18, 'min_samples_leaf': 21}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:30,664] Trial 76 finished with value: -1.6960804867108805 and parameters: {'n_estimator': 754, 'max_depth': 50, 'min_samples_split': 18, 'min_samples_leaf': 11}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:34,144] Trial 77 finished with value: -0.6212858490422832 and parameters: {'n_estimator': 816, 'max_depth': 21, 'min_samples_split': 15, 'min_samples_leaf': 3}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:34,651] Trial 78 finished with value: -2.445045426705429 and parameters: {'n_estimator': 122, 'max_depth': 49, 'min_samples_split': 27, 'min_samples_leaf': 23}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:36,651] Trial 79 finished with value: -1.455673078541469 and parameters: {'n_estimator': 468, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:39,138] Trial 80 finished with value: -1.5159027269864471 and parameters: {'n_estimator': 594, 'max_depth': 39, 'min_samples_split': 22, 'min_samples_leaf': 9}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:42,986] Trial 81 finished with value: -2.3098121706880286 and parameters: {'n_estimator': 960, 'max_depth': 40, 'min_samples_split': 19, 'min_samples_leaf': 20}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:44,900] Trial 82 finished with value: -2.5903658016861586 and parameters: {'n_estimator': 478, 'max_depth': 20, 'min_samples_split': 13, 'min_samples_leaf': 25}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:45,457] Trial 83 finished with value: -0.27052545998656596 and parameters: {'n_estimator': 112, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:49,269] Trial 84 finished with value: -0.7401008960005875 and parameters: {'n_estimator': 870, 'max_depth': 38, 'min_samples_split': 16, 'min_samples_leaf': 4}. Best is trial 72 with value: -0.2615601115545077.
[I 2026-03-12 03:51:51,471] Trial 85 finished with value: -1.9903721935258847 and parameters: {'n_estimator': 542, 'max_depth': 29, 'min_samples_split': 7, 'min_samples_leaf': 14}. Best is trial 72 with value: -0.2615601115545077.

In [24]:
study.best_params

{'n_estimator': 940,
 'max_depth': 45,
 'min_samples_split': 3,
 'min_samples_leaf': 1}

In [25]:
best_params = study.best_params

In [26]:
import matplotlib.pyplot as plt

In [28]:
optuna.visualization.plot_optimization_history(study)

In [29]:
optuna.visualization.plot_parallel_coordinate(study)

In [31]:
optuna.visualization.plot_slice(study, params=['n_estimator','max_depth','min_samples_split','min_samples_leaf'])

In [32]:
optuna.visualization.plot_param_importances(study)

In [35]:
best_n_estimators = best_params['n_estimator']
best_max_depth = best_params['max_depth']
best_min_samples_split = best_params['min_samples_split']
best_min_samples_leaf= best_params['min_samples_leaf']

In [36]:
best_model = RandomForestRegressor(n_estimators=best_n_estimators,
                                  max_depth=best_max_depth,
                                  min_samples_split=best_min_samples_split,
                                  min_samples_leaf=best_min_samples_leaf)

In [37]:
best_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=45, min_samples_split=3, n_estimators=940)

In [38]:
y_pred = best_model.predict(X_test)

In [39]:
mean_absolute_error(y_test, y_pred)

0.3239366038806912

In [40]:
mean_squared_error(y_test, y_pred)

0.16482445773479967

In [41]:
r2_score(y_test, y_pred)

0.9826217317884018